theme: jekyll-theme-slate
include:
  - assets
  - README.md
remote_theme: pages-themes/leap-day@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: GTA Computer
description: am S.-v.-Pufendorf-Gymnasium in Flöha/Sachsen
show_downloads: false